name: Go

on:
  push:
    branches: [ master,dockerize ]
  pull_request:
    branches: [ master,dockerize ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -tags skip ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Calc coverage
      run: go test -v -covermode=count -coverprofile=coverage.out -tags skip ./...
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.8
      with:
        infile: coverage.out        # optional, default filename is `coverage.out`
        outfile: coverage.lcov      # optional, default filename is `coverage.lcov`
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov

  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      if: success()
      uses: docker/build-push-action@v2.3.0
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: gogems/jet:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}